version: '3.3'
services:
  pms-docker:
    container_name: plex
    devices:
      - /dev/dri:/dev/dri
#    runtime: nvidia
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Denver
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - PLEX_CLAIM=$PLEXCLAIM
    networks:
      - internal
      - external
    volumes:
      - $DOCKERPATH/plex/database:/config
      - /dev/shm:/transcode
      - $MEDIAPATH:/mnt/unionfs/Media
    restart: always
    image: plexinc/pms-docker
  overseerr:
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    ports:
      - 5055:5055
    volumes:
      - $DOCKERPATH/overseerr/config:/config
    networks:
      - internal
    restart: unless-stopped
    image: linuxserver/overseerr
  speedtest:
    container_name: speedtest
    ports:
      - 8223:8223
    environment:
      - PUID=1000
      - PGID=1000
      - TITLE=$DOMAINNAME
      - WEBPORT=8223
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    restart: always
    image: adolfintel/speedtest
  app:
    image: nextcloud
    restart: always
    ports:
      - 8087:80
    links:
      - ncdb
    volumes:
      - /opt/docker/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=$NCDBUSER
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - internal
  ncdb:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NCDBROOT
      - MYSQL_PASSWORD=$NCDBUSER
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal
networks:
  internal:
    external: true
  external:
    external: true
