version: '2'

volumes:
  nextcloud:
  db:

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8087:80
    links:
      - db
    volumes:
      - /opt/docker/nextcloud/html:/var/www/html
      - /mnt/Storage/NextCloud:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=$NCDBUSER
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - internal
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NCDBROOT
      - MYSQL_PASSWORD=$NCDBUSER
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal

networks:
  internal:
    external: true