services:
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    profiles: [seafile]
    restart: always
    ports:
      - 8088:80
    depends_on:
      - seafile-db
      - seafile-memcached
    volumes:
      - ${DOCKERPATH}/seafile/data:/shared
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=${SEAFILE_DB_ROOT_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME}
      - TIME_ZONE=${TZ}
    networks:
      - internal
    labels:
      - wud.watch=true

  seafile-db:
    image: mariadb:10.11
    container_name: seafile-db
    profiles: [seafile]
    restart: always
    volumes:
      - ${DOCKERPATH}/seafile/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    networks:
      - internal
    labels:
      - wud.watch=true

  seafile-memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    profiles: [seafile]
    restart: always
    entrypoint: memcached -m 256
    networks:
      - internal
    labels:
      - wud.watch=true

networks:
  internal:
    external: true
