version: '3.3'
services:
    radarr:
        container_name: radarr
        ports:
            - 7878:7878
        environment:
            - PUID=1000
            - PGID=1000
            - HOME=/root
            - TERM=xterm
            - XDG_CONFIG_HOME=/config/xdg
            - LANGUAGE=en_US.UTF-8
            - LANG=en_US.UTF-8
        volumes:
          - /etc/localtime:/etc/localtime
          - $DOCKERPATH/radarr:/config
          - $MEDIAPATH:/mnt/Media
        networks:
          - internal
        restart: always
        image: 'linuxserver/radarr:latest'
networks:
  internal:
    external: true