services:
  portainer-ce:
    container_name: portainer
    profiles: [portainer]
    ports:
      - 9000:9000
    privileged: false
    entrypoint:
      - /portainer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERPATH}/portainer/data:/data
    networks:
      - internal
    restart: always
    image: portainer/portainer-ce
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    container_name: watchtower
    profiles: [watchtower]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_LABEL_ENABLE=true
    image: containrrr/watchtower
  netdata:
    container_name: netdata
    profiles: [netdata]
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    restart: always
    image: titpetric/netdata
    labels:
      - com.centurylinklabs.watchtower.enable=true
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    profiles: [duckdns]
    networks:
      - external
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DOMAINNAME}
      - TOKEN=${DUCKDNSTOKEN}
      - LOG_FILE=false
    volumes:
      - ${DOCKERPATH}/duckdns:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    profiles: [cloudflared]
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - external
    labels:
      - com.centurylinklabs.watchtower.enable=true
  uptime-kuma:
    restart: always
    profiles: [uptime-kuma]
    ports:
      - 3001:3001
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERPATH}/uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    labels:
      - com.centurylinklabs.watchtower.enable=true
  speedtest:
    container_name: speedtest
    profiles: [speedtest]
    ports:
      - 8223:8223
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TITLE=${DOMAINNAME}
      - WEBPORT=8223
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    restart: always
    image: adolfintel/speedtest
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  internal:
    external: true
  external:
    external: true
